//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELCSADataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Congregant
    {
        public string Congregant_ID { get; set; }
        public string Con_Name { get; set; }
        public string Con_Surname { get; set; }
        public string Con_Phone_Number { get; set; }
        public string Con_Ward { get; set; }
        public Nullable<int> Con_Age { get; set; }
        public int Parish_ID { get; set; }
    }
}
