//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELCSADataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELCSAEntities : DbContext
    {
        public ELCSAEntities()
            : base("name=ELCSAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Congregant> Congregants { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<OfficeWorker> OfficeWorkers { get; set; }
        public virtual DbSet<Parish> Parishes { get; set; }
        public virtual DbSet<Pastor> Pastors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
