//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELCSADataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeWorker
    {
        public string emp_ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone_Number { get; set; }
        public string ID_Number { get; set; }
    }
}
