//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELCSADataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parish
    {
        public int Parish_ID { get; set; }
        public string Parish_Name { get; set; }
        public string Parish_Pastor { get; set; }
        public string Parish_Address { get; set; }
        public string Pasrish_Cell { get; set; }
        public string Congregant_ID { get; set; }
    }
}
