//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELCSADataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pastor
    {
        public string emp_ID { get; set; }
        public string P_Name { get; set; }
        public string P_Surname { get; set; }
        public string P_PhoneNumber { get; set; }
        public string P_ID_Number { get; set; }
        public int Parish_ID { get; set; }
    }
}
