//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELCSAEntities : DbContext
    {
        public ELCSAEntities()
            : base("name=ELCSAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Congregant> Congregants { get; set; }
        public virtual DbSet<Parish2_0> Parish2_0 { get; set; }
        public virtual DbSet<Pastor> Pastors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
